# ==========================
# List of plugins
# ==========================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux#v2.3.0'

# ==========================
# Plugins configurations
# ==========================

# Catpuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g @catppuccin_flavor 'mocha' 
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# ==========================
# Tmux keybinds + config
# ==========================
# Status bar
# Move the status bar to the top
set-option -g status-position top

# Unbind the default Ctrl+b and set Ctrl+s as the new prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"

# Ctrl+s, h/j/k/l to move left/down/up/right
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Ctrl+s, Shift+h/j/k/l to resize panels
# The '-r' flag allows you to press and hold the key to repeat the resize 
# without having to press the Ctrl+s prefix again for every single step.
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Open new panes and windows in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
